GET http://localhost:5000/orgname/reponame/snapshots/12345?commit=usgf873ewfewr&release=qqq&workflow=mmmmm&branch=master&run=98765

###

POST http://localhost:5000/orgname/reponame/snapshots
content-type: application/json

{
    "locations": [
        {
            "path": "path/to/metadata/file/package.json",
            "components": [
                {
                    "coordinates": {
                        "type": "npm",
                        "name": "express",
                        "version": "4.0.0"
                    },
                    "usage": {
                        "devDependency": false
                    },
                    "dependencies": [{
                      "coordinates": {
                        "type": "npm",
                            "name": "ajv",
                            "version": "6.11.0"
                      }
                    }],
                    "directDependency": true
                }
            ]
        }
    ],
    "metadata": {
        "commit": "jgljlgjrgjortgrtop",
        "branch": "master",
        "release": "",
        "workflow": "123",
        "run": "567"
    }
}

###
